package com.ironhack.ironhack.controller;


import com.ironhack.ironhack.Enums.Status;
import com.ironhack.ironhack.model.Employee;
import com.ironhack.ironhack.model.Patient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.util.*;

@RestController
public class HospitalController {
    private final Map<Long, Employee> employees = new HashMap<>();
    private final Map<Long, Patient> patients = new HashMap<>();

    public HospitalController() {
        //This objects generated by ai not manually )) I think it is not a problem
        Employee e1 = new Employee(356712, "cardiology", "Alonso Flores", Status.ON_CALL);
        Employee e2 = new Employee(564134, "immunology", "Sam Ortega", Status.ON);
        Employee e3 = new Employee(761527, "cardiology", "German Ruiz", Status.OFF);
        Employee e4 = new Employee(166552, "pulmonary", "Maria Lin", Status.ON);
        Employee e5 = new Employee(156545, "orthopaedic", "Paolo Rodriguez", Status.ON_CALL);
        Employee e6 = new Employee(172456, "psychiatric", "John Paul Armes", Status.OFF);



        Patient p1 = new Patient(1, "Jaime Jordan", LocalDate.parse("1984-03-02"), 564134);
        Patient p2 = new Patient(2, "Marian Garcia", LocalDate.parse("1972-01-12"), 564134);
        Patient p3 = new Patient(3, "Julia Dusterdieck", LocalDate.parse("1954-06-11"), 356712);
        Patient p4 = new Patient(4, "Steve McDuck", LocalDate.parse("1931-11-10"), 761527);
        Patient p5 = new Patient(5, "Marian Garcia", LocalDate.parse("1999-02-15"), 172456);

        //Lets Objects pass to HashMap

        employees.put(e1.getEmployee_id(), e1);
        employees.put(e2.getEmployee_id(), e2);
        employees.put(e3.getEmployee_id(), e3);
        employees.put(e4.getEmployee_id(), e4);
        employees.put(e5.getEmployee_id(), e5);
        employees.put(e6.getEmployee_id(), e6);



        patients.put(p1.getPatient_id(), p1);
        patients.put(p2.getPatient_id(), p2);
        patients.put(p3.getPatient_id(), p3);
        patients.put(p4.getPatient_id(), p4);
        patients.put(p5.getPatient_id(), p5);

    }

    @GetMapping("/employees")
    public Collection<Employee> getAllEmployees() {
        return employees.values();  // Collection<Employee> qaytarır
    }

    @GetMapping("/patients")
    public Collection<Patient> getallPAtients() {
        return patients.values();


    }

    @GetMapping("/employees/{id}")
    public Employee getDoctorById(@PathVariable long id) {
        Employee doctor = employees.get(id);
        if (doctor == null) {
            throw new RuntimeException("Doctor not found with id: " + id);
        }
        return doctor;
    }

    @GetMapping("/patients/{patient_id}")
    public Patient getPatientById(@PathVariable long patient_id){
        Patient patient = patients.get(patient_id);
        return patient;
    }

    @GetMapping("/employees/status/{status}")
    public List<Employee> getEmployeeByStatus(@PathVariable Status status){
        List<Employee> result = new ArrayList<>();
        for(Employee employee : employees.values()){
            if(employee.getStatus() == status){
                result.add(employee);
            }
        }
        return result;
    }


    @GetMapping("/employees/departments/{department}")
    public List<Employee> getEmployeesByDepartment(@PathVariable String department){
        List<Employee> result = new ArrayList<>();
        for(Employee employee : employees.values()){
            if(employee.getDepartment() == department){
                result.add(employee);
            }

        }
        return result;
    }

    @GetMapping("/patients/status/off")
    public List<Employee> getAllPatientsByStatusisOFF(@PathVariable Status status){
        List<Employee> result = new ArrayList<>();
        for (Employee employee : employees.values()){
            if(employee.getStatus() == Status.OFF){
                result.add(employee);
            }
        }
        return result;
    }






}
